# flake8: noqa
ASR_SEARCH_URL = 'https://wireless2.fcc.gov/UlsApp/AsrSearch/asrRegistrationSearch.jsp'
FCC_DATA_URL = 'ftp://wirelessftp.fcc.gov/pub/uls/complete/a_tower.zip'
URL_MAP = {
        'American Towers LLC': 'https://www.americantower.com/index.html',
        'Global Tower, LLC. through American Towers, LLC': 'https://www.americantower.com/index.html',
        'American Towers, LLC': 'https://www.americantower.com/index.html',
        'SpectraSite Communications, LLC. through American Towers, LLC.': 'https://www.americantower.com/index.html',
        'American Towers, Inc.': 'https://www.americantower.com/index.html',
        'American Towers, LLC.': 'https://www.americantower.com/index.html',
        'American Tower Limited Partnership': 'https://www.americantower.com/index.html',
        'American Tower through UNIsite, Inc.': 'https://www.americantower.com/index.html',
        'Spectrasite Communications, Inc. through American Tower, Inc.': 'https://www.americantower.com/index.html',
        'American Towers L.L.C': 'https://www.americantower.com/index.html',

        'Cellco Partnership': 'https://www.verizon.com',
        'Cellco Partnership dba Verizon Wireless': 'https://www.verizon.com',
        'Alltel Corporation': 'https://www.verizon.com',
        'ALLTEL Communications, LLC': 'https://www.verizon.com',
        'Alltel Communications of Nebraska, Inc.': 'https://www.verizon.com',
        'Alltel Communications of the Southwest Limited Partnership': 'https://www.verizon.com',
        'ALLTEL Communications of Arkansas RSA #12 Cellular Limited Partnership': 'https://www.verizon.com',
        'ALLTEL COMMUNICATIONS OF NORTH CAROLINA LIMITED PARTNERSHIP': 'https://www.verizon.com',
        'Alltel Communications Wireless, Inc.': 'https://www.verizon.com',
        'Radiofone, Inc. d/b/a Alltel': 'https://www.verizon.com',
        'Alltel Communications of Virginia No. 1, LLC': 'https://www.verizon.com',
        'Alltel Communications of North Carolina Limited Partnership': 'https://www.verizon.com',
        'Alltel Communications of Virginia, Inc.': 'https://www.verizon.com',
        'Alltel Communications of Nebraska, LLC': 'https://www.verizon.com',
        'Alltel Cellular Associates of Arkansas Limited Partnership': 'https://www.verizon.com',

        'Crown Castle South LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle GT Company LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Communications LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Atlantic Company LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle Towers 06-2 LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle Towers 05 LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Communication LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Communication Inc.': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle MU LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN CASTLE GT COMPANY LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Communication Inc': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle PR LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Atlantic Company, LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN ATLANTIC COMPANY, LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle Fiber LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN COMMUNICATION INC.': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle Fiber Holdings, Corp.': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN COMMUNICATION LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN CASTLE PT, INC.': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle USA Inc.': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN CASTLE TOWERS 06-2 LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Crown Castle Towers 09 LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN CASTLE TOWER 05 LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CROWN ATLANTIC COMPANY LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CCATT LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'CCATT PR LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',
        'Pinnacle Towers LLC': 'https://www.facebook.com/Crown-Castle-857671374331148',

        'SBA 2012 TC Assets, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers II LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Structures, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Properties, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Monarch Towers I, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Monarch Towers III, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers III LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers IX, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Infrastructures, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers IV, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers V, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers X, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers VI, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA TOWERS INC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA GC Towers, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Steel, LLC.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Steel LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers II, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Properties, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA TOWERS, INC.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers VII, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Puerto Rico, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Monarch Towers II, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Puerto Rico, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Sites, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Structures, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA 2012 TC II, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Puerto Rico': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Steel, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers III, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA 2012 TC Assets PR, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA USVI, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Steel II, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers, Inc': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers VIII, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers USVI, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Structures, Inc': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Properties, Inc': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Properties': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA, INC.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers USVI, Inc': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Towers II LLCq': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Tower II LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA TOWERS INCORPORATED': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA TC Assets, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA TC Acquisitions, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Sites, Inc.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA STRUCTURES, INC.': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Properties Louisiana LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Monarch Toewrs III, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Infrastructure, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA Central Acquisition 2015, LLC': 'https://www.sbasite.com/English/home/default.aspx',
        'SBA 2014 PR, Inc.': 'https://www.sbasite.com/English/home/default.aspx',

        'Tillman Infrastructure, LLC': 'https://www.tillmaninfrastructure.com',
        'Tillman Infrastructure LLC': 'https://www.tillmaninfrastructure.com',
        'Tillman Infrastructure,LLC': 'https://www.tillmaninfrastructure.com',
        'Tillman Infrastructure': 'https://www.tillmaninfrastructure.com',

        'UNITED STATES CELLULAR CORPORATION': 'https://www.facebook.com/USCellular',
        'United States Cellular Corporation': 'https://www.facebook.com/USCellular',
        }

TYPE_MAP = {
        'B': 'Building',
        'BANT': 'Building with Antenna on top',
        'BMAST': 'Building with Mast',
        'BPIPE': 'Building with Pipe',
        'BPOLE': 'Building with Pole',
        'BRIDG': 'Bridge',
        'BTWR': 'Building with Tower',
        'GTOWER': 'Guyed Structure Used for Commun',
        'LTOWER': 'Lattice Tower',
        'MAST': 'Mast',
        'MTOWER': 'Monopole',
        'NNGTANN': 'Guyed Tower Array',
        'NNLTANN': 'Lattice Tower Array',
        'NNMTANN': 'Monopole Array',
        'PIPE': 'Any type of Pipe',
        'POLE': 'Any type of Pole',
        'RIG': 'Oil or other type of Rig',
        'SIGN': 'Any Type of Sign or Billboard',
        'SILO': 'Any type of Silo',
        'STACK': 'Smoke Stack',
        'TANK': 'Any type of Tank (Water, Gas, etc)',
        'TREE': 'When used as a support for an ant',
        'UPOLE': 'Utility Pole/Tower used to provide',
        'UNKN': 'Unknown',
        }
