# Generated by Django 3.1.1 on 2020-10-27 00:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import towerlocator.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TowerLocatorMarket',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('height', models.FloatField()),
                ('coverage', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('task', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('token', models.CharField(default=towerlocator.models.createTokenDefault, editable=False, max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
