# Generated by Django 3.1.1 on 2021-03-11 01:58
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('last_edited', models.DateField(auto_now_add=True)),
                ('map_center', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-97.03125, 36.59788913307022), srid=4326)),
                ('zoom_level', models.FloatField(default=3.75)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('installation_height', models.FloatField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='PTPLink',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.FloatField(default=2.4)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptplinks', to='workspace.network')),
                ('radios', models.ManyToManyField(to='workspace.Radio')),
            ],
        ),
        migrations.CreateModel(
            name='ISPCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('employees', models.ManyToManyField(through='workspace.Employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.ispcompany'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
