# Generated by Django 3.1.1 on 2021-03-08 22:36

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msftid', models.IntegerField(blank=True, null=True)),
                ('geog', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('status', models.CharField(choices=[(workspace.models.CoverageStatus['SERVICEABLE'], 'serviceable'), (workspace.models.CoverageStatus['UNSERVICEABLE'], 'unserviceable'), (workspace.models.CoverageStatus['UNKNOWN'], 'unknown')], default=workspace.models.CoverageStatus['UNKNOWN'], max_length=20)),
                ('height_margin', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPointLocation',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('max_radius', models.FloatField()),
                ('no_check_radius', models.FloatField()),
                ('default_cpe_height', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessPointCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(workspace.models.CoverageCalculationStatus['START'], 'Started'), (workspace.models.CoverageCalculationStatus['FAIL'], 'Failed'), (workspace.models.CoverageCalculationStatus['COMPLETE'], 'Complete')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation')),
                ('nearby_buildings', models.ManyToManyField(related_name='nearby_buildings', to='workspace.BuildingCoverage')),
            ],
        ),
    ]
