# Generated by Django 3.1.1 on 2021-03-09 17:05

from django.db import migrations, models
import workspace.models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_accesspointcoverage_accesspointlocation_buildingcoverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointcoverage',
            name='status',
            field=models.CharField(choices=[(workspace.models.CoverageCalculationStatus['START'], 'Started'), (workspace.models.CoverageCalculationStatus['FAIL'], 'Failed'), (workspace.models.CoverageCalculationStatus['COMPLETE'], 'Complete')], default='Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='buildingcoverage',
            name='status',
            field=models.CharField(choices=[(workspace.models.CoverageStatus['SERVICEABLE'], 'serviceable'), (workspace.models.CoverageStatus['UNSERVICEABLE'], 'unserviceable'), (workspace.models.CoverageStatus['UNKNOWN'], 'unknown')], default='unknown', max_length=20),
        ),
    ]
