# Generated by Django 3.1.1 on 2021-03-24 00:14
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import workspace.models.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0004_auto_20210323_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkMapPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-97.03125, 36.59788913307022), srid=4326)),
                ('zoom', models.FloatField(default=3.75, validators=[workspace.models.validators.validate_zoom_level])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
