# Generated by Django 3.1.6 on 2021-03-31 20:49

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workspace.models.network_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0006_cpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='APToCPELink',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.FloatField(default=2.4)),
                ('geojson', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            bases=(models.Model, workspace.models.network_models.GeoJSONModel),
        ),
        migrations.CreateModel(
            name='CPELocation',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('height', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('geojson', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, workspace.models.network_models.GeoJSONModel),
        ),
        migrations.RenameField(
            model_name='accesspointlocation',
            old_name='location',
            new_name='geojson',
        ),
        migrations.DeleteModel(
            name='CPE',
        ),
        migrations.AddField(
            model_name='aptocpelink',
            name='ap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation'),
        ),
        migrations.AddField(
            model_name='aptocpelink',
            name='cpe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.cpelocation'),
        ),
        migrations.AddField(
            model_name='aptocpelink',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
