# Generated by Django 3.1.8 on 2021-04-21 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0008_auto_20210401_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointCoverageBuildings',
            fields=[
                ('ap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='workspace.accesspointlocation')),
                ('status', models.CharField(choices=[('Started', 'Start'), ('Failed', 'Fail'), ('Complete', 'Complete')], default='Started', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buildingcoverage',
            name='status',
            field=models.CharField(choices=[('serviceable', 'Serviceable'), ('unserviceable', 'Unserviceable'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.DeleteModel(
            name='AccessPointCoverage',
        ),
        migrations.AddField(
            model_name='accesspointcoveragebuildings',
            name='nearby_buildings',
            field=models.ManyToManyField(related_name='nearby_buildings', to='workspace.BuildingCoverage'),
        ),
    ]
