# Generated by Django 3.1.8 on 2021-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0009_auto_20210421_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptocpelink',
            name='frequency',
            field=models.FloatField(default=2.437),
        ),
    ]
