# Generated by Django 3.1.8 on 2021-05-11 22:25

import IspToolboxApp.util.s3
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_auto_20210430_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewshedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text='\n            This hash helps determine if the AP has already been computed.\n        ', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('VISIBLE', 'Visible'), ('DEM', 'Dem'), ('GROUND', 'Ground'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('ap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation')),
            ],
            bases=(models.Model, IspToolboxApp.util.s3.S3PublicExportMixin),
        ),
    ]
