# Generated by Django 3.1.8 on 2021-05-14 16:43
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_viewshedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointcoveragebuildings',
            name='hash',
            field=models.CharField(default='', help_text='\n            Hashvalue to determine if result has already been calculated\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='cpelocation',
            name='height',
            field=models.FloatField(help_text='\n        This height value is relative to the terrain\n        '),
        ),
    ]
