# Generated by Django 3.1.8 on 2021-05-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_auto_20210514_1643'),
        ('workspace', '0009_multiplayersession'),
    ]

    operations = [
    ]
