# Generated by Django 3.1.8 on 2021-05-17 21:27
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import uuid
import workspace.models.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0012_auto_20210514_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMapSession',
            fields=[
                ('name', models.CharField(default='untitled workspace', max_length=255)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('center', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-97.03125, 36.59788913307022), srid=4326)),
                ('zoom', models.FloatField(default=3.75, validators=[workspace.models.validators.validate_zoom_level])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
