# Generated by Django 3.1.8 on 2021-05-20 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_auto_20210519_0559'),
        ('workspace', '0013_merge_20210519_1811'),
    ]

    operations = [
    ]
