# Generated by Django 3.1.8 on 2021-06-01 16:45

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0015_merge_20210520_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacemapsession',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-97.03125, 36.59789), srid=4326),
        ),
    ]
