# Generated by Django 3.1.8 on 2021-06-02 22:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0017_accesspointbasedcoveragearea_coveragearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointbasedcoveragearea',
            name='geojson',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326),
        ),
    ]
