# Generated by Django 3.1.8 on 2021-06-07 23:08

import IspToolboxApp.util.s3
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0018_auto_20210602_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewshed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('hash', models.CharField(help_text='\n            This hash helps determine if the AP has already been computed.\n        ', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('VISIBLE', 'Visible'), ('DEM', 'Dem'), ('GROUND', 'Ground'), ('NORMAL', 'Normal')], default='NORMAL', max_length=20)),
                ('ap', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation')),
            ],
            bases=(models.Model, IspToolboxApp.util.s3.S3PublicExportMixin),
        ),
        migrations.CreateModel(
            name='ViewshedTile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tile', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='isptoolbox-tilesets'), upload_to='')),
                ('viewshed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.viewshed')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, IspToolboxApp.util.s3.S3PublicExportMixin),
        ),
        migrations.DeleteModel(
            name='ViewshedModel',
        ),
    ]
