# Generated by Django 3.1.9 on 2021-06-08 17:38
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models
import storages.backends.s3boto3
import workspace.models.viewshed_models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0019_auto_20210607_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewshedtile',
            name='tile',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='isptoolbox-tilesets'), upload_to=workspace.models.viewshed_models.ViewshedTile.upload_to_path),
        ),
    ]
