# Generated by Django 3.1.12 on 2021-06-16 03:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0022_auto_20210611_2336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workspacemapsession',
            unique_together={('owner', 'name')},
        ),
    ]
