# Generated by Django 3.1.12 on 2021-06-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('workspace', '0024_coveragearea_uneditable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptocpelink',
            name='geojson',
        ),
        migrations.AddField(
            model_name='workspacemapsession',
            name='logging_fbid',
            field=models.BigIntegerField(default=None, help_text="fbid for logging purposes, don't trust", null=True),
        ),
        migrations.AddField(
            model_name='workspacemapsession',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AddField(
            model_name='workspacemapsession',
            name='units',
            field=models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='IMPERIAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='accesspointbasedcoveragearea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesspointbasedcoveragearea',
            name='session',
            field=models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession'),
        ),
        migrations.AlterField(
            model_name='accesspointlocation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accesspointlocation',
            name='session',
            field=models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession'),
        ),
        migrations.AlterField(
            model_name='aptocpelink',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aptocpelink',
            name='session',
            field=models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession'),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coveragearea',
            name='session',
            field=models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession'),
        ),
        migrations.AlterField(
            model_name='cpelocation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cpelocation',
            name='session',
            field=models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession'),
        ),
        migrations.AlterField(
            model_name='workspacemapsession',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
