# Generated by Django 3.1.12 on 2021-06-21 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0024_cookie_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptocpelink',
            name='geojson',
        ),
    ]
