# Generated by Django 3.1.12 on 2021-06-23 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0025_auto_20210623_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesspointbasedcoveragearea',
            old_name='session',
            new_name='map_session',
        ),
        migrations.RenameField(
            model_name='accesspointlocation',
            old_name='session',
            new_name='map_session',
        ),
        migrations.RenameField(
            model_name='aptocpelink',
            old_name='session',
            new_name='map_session',
        ),
        migrations.RenameField(
            model_name='coveragearea',
            old_name='session',
            new_name='map_session',
        ),
        migrations.RenameField(
            model_name='cpelocation',
            old_name='session',
            new_name='map_session',
        ),
    ]
