# Generated by Django 3.1.12 on 2021-06-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0024_coveragearea_uneditable'),
        ('workspace', '0025_remove_aptocpelink_geojson'),
    ]

    operations = [
    ]
