# Generated by Django 3.1.12 on 2021-06-30 21:52
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0027_auto_20210623_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoverageArea',
            new_name='PolygonCoverageArea',
        ),
        migrations.AddField(
            model_name='accesspointbasedcoveragearea',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accesspointlocation',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aptocpelink',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpelocation',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
    ]
