# Generated by Django 3.1.12 on 2021-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0031_auto_20210701_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointbasedcoveragearea',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aptocpelink',
            name='uneditable',
            field=models.BooleanField(default=False),
        ),
    ]
