# Generated by Django 3.1.12 on 2021-07-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0032_auto_20210701_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpelocation',
            name='ap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation'),
        ),
    ]
