# Generated by Django 3.1.12 on 2021-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0033_cpelocation_ap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpelocation',
            name='height',
            field=models.FloatField(help_text='\n        This height value is relative to the terrain in meters. When object is first created the height field\n        is taken from the AP "default_cpe_height", it is then converted to DTM height. The following\n        saves are all relative to terrain.\n        '),
        ),
    ]
