# Generated by Django 3.1.12 on 2021-07-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0034_auto_20210713_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointlocation',
            name='default_cpe_height',
            field=models.FloatField(default=1),
        ),
    ]
