# Generated by Django 3.1.12 on 2021-07-22 20:47
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0035_auto_20210713_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesspointlocation',
            name='cloudrf_coverage_geojson',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(null=True, srid=4326),
        ),
    ]
