# Generated by Django 3.1.12 on 2021-07-22 23:20
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0036_accesspointlocation_cloudrf_coverage_geojson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPointBasedCoverageArea',
        ),
    ]
