# Generated by Django 3.1.12 on 2021-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0037_delete_accesspointbasedcoveragearea'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemapsession',
            name='lock_dragging',
            field=models.BooleanField(default=False),
        ),
    ]
