# Generated by Django 3.1.12 on 2021-09-09 19:01
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0039_auto_20210908_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointlocation',
            name='height',
            field=models.FloatField(default=30),
        ),
        migrations.AlterField(
            model_name='accesspointlocation',
            name='max_radius',
            field=models.FloatField(default=2),
        ),
    ]
