# Generated by Django 3.1.12 on 2021-09-21 17:02
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0040_auto_20210909_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointlocation',
            name='name',
            field=models.CharField(default='Unnamed AP', max_length=50),
        ),
    ]
