# Generated by Django 3.1.13 on 2021-09-23 05:51
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3boto3
import uuid
import workspace.models.ayi_dyi_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_celery_results', '0010_remove_duplicate_indices'),
        ('workspace', '0041_auto_20210921_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteInformationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('task', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_results.taskresult')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessInformationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, default=None, null=True)),
                ('task_id', models.CharField(blank=True, default=None, help_text='Celery ID for the Task that was run', max_length=255, null=True, unique=True, verbose_name='Task ID')),
                ('data_dump', models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='isptoolbox-export-file'), upload_to=workspace.models.ayi_dyi_models.AccessInformationJob.access_your_info_path)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
