# Generated by Django 3.1.13 on 2021-09-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0042_accessinformationjob_deleteinformationjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleteinformationjob',
            name='task',
        ),
        migrations.AddField(
            model_name='deleteinformationjob',
            name='task_id',
            field=models.CharField(blank=True, default=None, help_text='Celery ID for the Task that was run', max_length=255, null=True, unique=True, verbose_name='Task ID'),
        ),
    ]
