# Generated by Django 3.1.13 on 2021-10-01 19:48
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0042_auto_20210924_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragearea',
            name='geo_overlay_type',
            field=models.CharField(choices=[('none', 'None'), ('rdof', 'Rdof'), ('census', 'Census'), ('community_connect', 'Community Connect'), ('cbrs', 'Cbrs'), ('tribal', 'Tribal')], default='none', max_length=20),
        ),
    ]
