# Generated by Django 3.1.13 on 2021-09-27 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0042_auto_20210924_1705'),
        ('workspace', '0043_auto_20210923_1834'),
    ]

    operations = [
    ]
