# Generated by Django 3.1.13 on 2021-10-02 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0043_analyticsevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsevent',
            old_name='eventType',
            new_name='event_type',
        ),
        migrations.RenameField(
            model_name='analyticsevent',
            old_name='sessionId',
            new_name='session_id',
        ),
    ]
