# Generated by Django 3.1.13 on 2021-10-05 20:26
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models
import storages.backends.s3boto3
import workspace.models.ayi_dyi_models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0044_merge_20210927_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessinformationjob',
            name='data_dump',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='isptoolbox-export-file', custom_domain=None, location=''), upload_to=workspace.models.ayi_dyi_models.AccessInformationJob.access_your_info_path),
        ),
    ]
