# Generated by Django 3.1.13 on 2021-10-05 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0044_merge_20210927_1336'),
        ('workspace', '0043_coveragearea_geo_overlay_type'),
    ]

    operations = [
    ]
