# Generated by Django 3.1.13 on 2021-10-05 18:55
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0045_merge_20211005_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coveragearea',
            name='geo_overlay_type',
        ),
        migrations.AddField(
            model_name='coveragearea',
            name='name',
            field=models.CharField(default='Area', max_length=50),
        ),
    ]
