# Generated by Django 3.1.13 on 2021-10-05 21:24
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0046_auto_20211005_1155'),
        ('workspace', '0045_auto_20211005_1326'),
    ]

    operations = [
    ]
