# Generated by Django 3.1.13 on 2021-10-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0047_merge_20211005_1424'),
        ('workspace', '0044_auto_20211002_0105'),
    ]

    operations = [
    ]
