# Generated by Django 3.1.13 on 2021-10-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0047_merge_20211005_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewshedtile',
            name='x',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='viewshedtile',
            name='y',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='viewshedtile',
            name='zoom',
            field=models.IntegerField(db_index=True),
        ),
    ]
