# Generated by Django 3.1.13 on 2021-10-09 00:01
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0048_add_index_fake'),
        ('workspace', '0044_auto_20211002_0105'),
    ]

    operations = [
    ]
