# Generated by Django 3.1.13 on 2021-10-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0049_merge_20211008_1701'),
        ('workspace', '0049_unique_together'),
    ]

    operations = [
    ]
