# Generated by Django 3.1.13 on 2021-10-13 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0052_auto_20211011_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyticsevent',
            name='created_at',
        ),
    ]
