# Generated by Django 3.1.13 on 2021-10-27 18:42
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0054_analyticsevent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointlocation',
            name='default_cpe_height',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0, message='Ensure this value is greater than or equal to %(limit_value)s m.'), django.core.validators.MaxValueValidator(1000, message='Ensure this value is less than or equal to %(limit_value)s. m')]),
        ),
        migrations.AlterField(
            model_name='accesspointlocation',
            name='height',
            field=models.FloatField(default=30, validators=[django.core.validators.MinValueValidator(0, message='Ensure this value is greater than or equal to %(limit_value)s m.'), django.core.validators.MaxValueValidator(1000, message='Ensure this value is less than or equal to %(limit_value)s. m')]),
        ),
        migrations.AlterField(
            model_name='accesspointlocation',
            name='max_radius',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(0, message='Ensure this value is greater than or equal to %(limit_value)s km.'), django.core.validators.MaxValueValidator(16, message='Ensure this value is less than or equal to %(limit_value)s. km')]),
        ),
    ]
