# Generated by Django 3.1.13 on 2021-11-17 22:20

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sessions', '0001_initial'),
        ('workspace', '0056_auto_20211028_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointToPointLink',
            fields=[
                ('uneditable', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('frequency', models.FloatField(default=2.437, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('geojson', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('map_session', models.ForeignKey(db_column='session', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.workspacemapsession')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(db_column='django_session', help_text='This is a django session - different than map session', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
