# Generated by Django 3.1.13 on 2021-11-18 18:17
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.gis.db.models.fields
from django.db import migrations
import workspace.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0058_auto_20211117_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtopointlink',
            name='geojson',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326, validators=[workspace.models.validators.validate_ptp_link_geometry]),
        ),
    ]
