# Generated by Django 3.1.13 on 2021-12-02 22:32
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0059_auto_20211118_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcoverage',
            name='cpe_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
