# Generated by Django 3.1.13 on 2021-12-06 21:36
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0071_auto_20211206_1250'),
        ('workspace', '0060_buildingcoverage_cpe_location'),
    ]

    operations = [
    ]
