# Generated by Django 3.1.13 on 2021-12-06 23:58
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0072_merge_20211206_1336'),
        ('workspace', '0061_auto_20211203_1548'),
    ]

    operations = [
    ]
