# Generated by Django 3.1.13 on 2021-12-15 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0073_merge_20211206_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointsector',
            name='azimuth',
            field=models.FloatField(default=120, validators=[django.core.validators.MinValueValidator(0.1, message='Ensure this value is greater than or equal to %(limit_value)s degrees.'), django.core.validators.MaxValueValidator(360, message='Ensure this value is less than or equal to %(limit_value)s degrees.')]),
        ),
        migrations.AlterField(
            model_name='accesspointsector',
            name='heading',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Ensure this value is greater than or equal to %(limit_value)s degrees.'), django.core.validators.MaxValueValidator(360, message='Ensure this value is less than or equal to %(limit_value)s degrees.')]),
        ),
    ]
