# Generated by Django 3.1.13 on 2021-12-21 00:04
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0074_auto_20211214_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointlocation',
            name='name',
            field=models.CharField(default='Unnamed AP', max_length=50, validators=[django.core.validators.MinLengthValidator(1, message='Ensure this value has length of at least %(limit_value)s characters.'), django.core.validators.MaxLengthValidator(50, message='Ensure this value has length at most %(limit_value)s characters.')]),
        ),
        migrations.AlterField(
            model_name='accesspointsector',
            name='azimuth',
            field=models.FloatField(default=120, validators=[django.core.validators.MinValueValidator(0.01, message='Ensure this value is greater than or equal to %(limit_value)s degrees.'), django.core.validators.MaxValueValidator(360, message='Ensure this value is less than or equal to %(limit_value)s degrees.')]),
        ),
    ]
