# Generated by Django 3.1.13 on 2021-12-16 22:55
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0074_auto_20211214_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewshed',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointsector'),
        ),
        migrations.AddField(
            model_name='viewshed',
            name='version',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='viewshed',
            name='ap',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation'),
        ),
    ]
