# Generated by Django 3.1.14 on 2021-12-22 23:02
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0075_auto_20211220_1604'),
        ('workspace', '0075_auto_20211216_1455'),
    ]

    operations = [
    ]
