# Generated by Django 3.1.14 on 2022-01-05 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0076_merge_20211222_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewshed',
            name='sector',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointsector'),
        ),
    ]
