# Generated by Django 3.1.14 on 2022-01-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0077_auto_20220105_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessPointCoverageBuildings',
        ),
    ]
