# Generated by Django 3.1.14 on 2022-01-10 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0078_delete_accesspointcoveragebuildings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPointCoverageBuildings',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Started', 'Start'), ('Failed', 'Fail'), ('Complete', 'Complete')], default='Started', max_length=20)),
                ('hash', models.CharField(default='', help_text='\n            Hashvalue to determine if result has already been calculated\n        ', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ap', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointlocation')),
                ('nearby_buildings', models.ManyToManyField(related_name='nearby_buildings', to='workspace.BuildingCoverage')),
                ('sector', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointsector')),
            ],
        ),
    ]
