# Generated by Django 3.1.14 on 2022-01-20 20:48
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0080_auto_20220120_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointsector',
            name='name',
            field=models.CharField(default='Unnamed AP', max_length=50),
        ),
    ]
