# Generated by Django 3.1.14 on 2022-01-21 23:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0081_auto_20220120_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointsector',
            name='cloudrf_coverage_geojson',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
