# Generated by Django 3.1.14 on 2022-01-24 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0083_cloudrfasynctaskmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudRFAsyncTaskModel',
        ),
    ]
