# Generated by Django 3.1.14 on 2022-01-31 23:31
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0086_auto_20220131_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewshed',
            name='progress_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='viewshed',
            name='time_remaining',
            field=models.FloatField(null=True),
        ),
    ]
