# Generated by Django 3.1.14 on 2022-02-01 22:40

import django.core.validators
from django.db import migrations, models
import workspace.models.network_models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0087_auto_20220131_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointsector',
            name='heading',
            field=models.FloatField(default=workspace.models.network_models.random_heading, validators=[django.core.validators.MinValueValidator(0, message='Ensure this value is greater than or equal to %(limit_value)s degrees.'), django.core.validators.MaxValueValidator(360, message='Ensure this value is less than or equal to %(limit_value)s degrees.')]),
        ),
    ]
