# Generated by Django 3.1.14 on 2022-02-22 23:30
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0089_auto_20220202_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemapsession',
            name='area_number',
            field=models.IntegerField(default=1),
        ),
    ]
