# Generated by Django 3.1.14 on 2022-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0090_workspacemapsession_area_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemapsession',
            name='area_number_gaps',
            field=models.CharField(default='[]', max_length=512),
        ),
    ]
