# Generated by Django 3.1.14 on 2022-02-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0091_workspacemapsession_area_number_gaps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspacemapsession',
            name='area_number_gaps',
        ),
    ]
