# Generated by Django 3.1.14 on 2022-02-23 18:36
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0093_remove_workspacemapsession_area_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemapsession',
            name='area_number',
            field=models.IntegerField(default=1),
        ),
    ]
