# Generated by Django 3.1.14 on 2022-03-02 19:44
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0095_remove_accesspointcoveragebuildings_nearby_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingcoverage',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workspace.accesspointcoveragebuildings'),
        ),
    ]
