# Generated by Django 3.1.14 on 2022-03-28 17:27
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0096_buildingcoverage_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesspointlocation',
            name='cloudrf_coverage_geojson',
        ),
        migrations.RemoveField(
            model_name='accesspointsector',
            name='cloudrf_coverage_geojson',
        ),
    ]
