# Generated by Django 3.1.14 on 2022-03-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0097_auto_20220328_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloudRFAsyncTaskModel',
        ),
    ]
