# Generated by Django 3.1.14 on 2022-04-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0101_asynctaskapimodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AsyncTaskAPIModel',
        ),
    ]
