# Generated by Django 3.1.14 on 2022-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0103_pointtopointserviceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesspointcoveragebuildings',
            name='hash',
            field=models.CharField(help_text='\n            This hash helps determine if the task result has already been computed.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='pointtopointserviceability',
            name='hash',
            field=models.CharField(help_text='\n            This hash helps determine if the task result has already been computed.\n        ', max_length=255),
        ),
        migrations.AlterField(
            model_name='viewshed',
            name='hash',
            field=models.CharField(help_text='\n            This hash helps determine if the task result has already been computed.\n        ', max_length=255),
        ),
    ]
