# Generated by Django 3.1.14 on 2022-04-08 21:51
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0104_auto_20220405_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PointToPointServiceability',
        ),
    ]
