# Generated by Django 3.0.8 on 2020-10-08 06:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msftcombined',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('geog', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'msftcombined',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TreeCanopy',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
                ('filename', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tree_canopy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TGLink',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=30, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tx', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('rx', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('building_start', models.BigIntegerField(blank=True, null=True)),
                ('building_end', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
