# Generated by Django 3.0.8 on 2020-10-09 16:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPTLidarPointCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8192)),
                ('id_num', models.IntegerField()),
                ('count', models.BigIntegerField()),
                ('url', models.URLField()),
                ('boundary', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('srs', models.IntegerField()),
            ],
        ),
    ]
