# Generated by Django 3.1.1 on 2021-03-16 05:14
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import secrets
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DSMConversionJob',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('access_token', models.CharField(default=secrets.token_urlsafe, editable=False, max_length=100)),
                ('area_of_interest', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('task', models.UUIDField(null=True)),
                ('error', models.CharField(default=None, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
