# Generated by Django 3.1.6 on 2021-03-25 17:41
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0002_dsmconversionjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptlidarpointcloud',
            name='valid',
            field=models.BooleanField(default=True, help_text='\n            Used to invalidate certain point clouds if the USGS says they are bad / have data issues\n        '),
        ),
    ]
