# Generated by Django 3.1.1 on 2020-10-15 21:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0002_eptlidarpointcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tglink',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
