# Generated by Django 3.1.8 on 2021-04-20 04:02
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0003_eptlidarpointcloud_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='USGSLidarMetaDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workunit', models.CharField(max_length=255)),
                ('workunit_id', models.IntegerField(null=True)),
                ('workpackage', models.CharField(max_length=255)),
                ('workpackage_id', models.IntegerField(null=True)),
                ('collect_start', models.CharField(max_length=255)),
                ('collect_end', models.CharField(max_length=255)),
                ('ql', models.CharField(max_length=255)),
                ('spec', models.CharField(max_length=255)),
                ('p_method', models.CharField(max_length=255)),
                ('dem_gsd_meters', models.FloatField(null=True)),
                ('horiz_crs', models.CharField(max_length=255)),
                ('vert_crs', models.CharField(max_length=255)),
                ('lpc_pub_date', models.CharField(max_length=255)),
                ('lpc_category', models.CharField(max_length=255)),
                ('lpc_reason', models.CharField(max_length=255)),
                ('opr_pub_date', models.CharField(max_length=255)),
                ('opr_category', models.CharField(max_length=255)),
                ('opr_reason', models.CharField(max_length=255)),
                ('onemeter_category', models.CharField(max_length=255)),
                ('onemeter_reason', models.CharField(max_length=255)),
                ('seamless_category', models.CharField(max_length=255)),
                ('seamless_reason', models.CharField(max_length=255)),
                ('lpc_link', models.CharField(max_length=255)),
                ('opr_link', models.CharField(max_length=255)),
                ('metadata_link', models.CharField(max_length=255)),
            ],
        ),
    ]
