# Generated by Django 3.1.1 on 2020-11-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0003_auto_20201015_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='tglink',
            name='fbid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
