# Generated by Django 3.1.1 on 2020-11-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0004_tglink_fbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOSSummary',
            fields=[
            ],
            options={
                'verbose_name': 'LOS Summary',
                'verbose_name_plural': 'LOS Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mmwave.tglink',),
        ),
    ]
