# Generated by Django 3.1.1 on 2020-12-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0005_lossummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eptlidarpointcloud',
            name='id_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
