# Generated by Django 3.1.1 on 2021-01-13 23:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0006_auto_20201216_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptlidarpointcloud',
            name='high_resolution_boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, null=True, srid=4326),
        ),
    ]
