# Generated by Django 3.1.1 on 2021-01-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0007_eptlidarpointcloud_high_resolution_boundary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tglink',
            name='building_end',
        ),
        migrations.RemoveField(
            model_name='tglink',
            name='building_start',
        ),
        migrations.AddField(
            model_name='tglink',
            name='freq',
            field=models.FloatField(default=0),
        ),
    ]
