# Generated by Django 3.1.8 on 2021-04-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0007_auto_20210420_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usgslidarmetadatamodel',
            name='lpc_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usgslidarmetadatamodel',
            name='metadata_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usgslidarmetadatamodel',
            name='opr_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
