# Generated by Django 3.1.1 on 2021-02-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0008_auto_20210125_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptlidarpointcloud',
            name='date_time_added_to_isptoolbox',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
