# Generated by Django 3.1.1 on 2021-02-23 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0009_eptlidarpointcloud_date_time_added_to_isptoolbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eptlidarpointcloud',
            name='date_time_added_to_isptoolbox',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
