# Generated by Django 3.1.1 on 2021-03-08 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0010_auto_20210223_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Msftcombined',
        ),
        migrations.DeleteModel(
            name='TreeCanopy',
        ),
    ]
