# Generated by Django 3.1.8 on 2021-04-28 18:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0010_eptlidarpointcloud_noisy_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usgslidarmetadatamodel',
            old_name='workpackage',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='usgslidarmetadatamodel',
            old_name='workpackage_id',
            new_name='project_id',
        ),
        migrations.AlterField(
            model_name='eptlidarpointcloud',
            name='count',
            field=models.BigIntegerField(help_text='Number of points in dataset'),
        ),
        migrations.AlterField(
            model_name='eptlidarpointcloud',
            name='high_resolution_boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, default=None, help_text='\n            Default boundary is low resolution and might miss some areas,\n            this is a higher resolution boundary that is expensive to produce\n        ', null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='usgslidarmetadatamodel',
            name='project',
            field=models.CharField(db_column='workpackage', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usgslidarmetadatamodel',
            name='project_id',
            field=models.IntegerField(db_column='workpackage_id', null=True),
        ),
    ]
