# Generated by Django 3.1.8 on 2021-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0011_auto_20210428_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='eptlidarpointcloud',
            name='inspected',
            field=models.BooleanField(default=False, help_text='\n            Point cloud has been inspected by admin for noisy data\n        '),
        ),
    ]
