# Generated by Django 3.1.8 on 2021-05-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0012_eptlidarpointcloud_inspected'),
    ]

    operations = [
        migrations.CreateModel(
            name='LidarTileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mmwave.eptlidarpointcloud')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
