# Generated by Django 3.1.8 on 2021-05-14 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0012_eptlidarpointcloud_inspected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewShedJob',
        ),
    ]
