# Generated by Django 3.1.8 on 2021-05-19 04:59
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0013_delete_viewshedjob'),
        ('mmwave', '0013_lidartilemodel'),
    ]

    operations = [
    ]
