# Generated by Django 3.1.12 on 2021-07-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmwave', '0017_auto_20210624_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='LidarDatasets',
            fields=[
            ],
            options={
                'verbose_name': 'LiDAR Dataset Summary',
                'verbose_name_plural': 'LiDAR Dataset Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mmwave.eptlidarpointcloud',),
        ),
    ]
