# Generated by Django 3.1.6 on 2021-03-30 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='IspToolboxUserSignUpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_website', models.CharField(max_length=100, null=True)),
                ('company_size', models.CharField(choices=[('aspiring', "I don't service anyone right now"), ('small', '1 - 100'), ('medium', '101 - 500'), ('large', '501 - 2,000'), ('xlarge', '2,001 - 5,000'), ('xxlarge', '+5,000')], default=None, max_length=50, null=True)),
                ('is_business_role', models.BooleanField()),
                ('is_tech_role', models.BooleanField()),
                ('is_sales_role', models.BooleanField()),
                ('is_goal_start', models.BooleanField()),
                ('is_goal_acquire_customers', models.BooleanField()),
                ('is_goal_expand', models.BooleanField()),
                ('ip_prefix', models.GenericIPAddressField()),
                ('ip_prefix_length', models.IntegerField()),
                ('asn', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
