# Generated by Django 3.1.6 on 2021-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0002_auto_20210330_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='asn',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='ip_prefix',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='ip_prefix_length',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_business_role',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_goal_acquire_customers',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_goal_expand',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_goal_start',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_sales_role',
        ),
        migrations.RemoveField(
            model_name='isptoolboxusersignupinfo',
            name='is_tech_role',
        ),
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='company_goal',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='individual_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='subscriber_size',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
