# Generated by Django 3.1.8 on 2021-05-11 00:32
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0003_auto_20210415_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isptoolboxusersignupinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
