# Generated by Django 3.1.12 on 2021-07-27 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0005_newuserexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserexperience',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
