# Generated by Django 3.1.12 on 2021-07-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0006_auto_20210727_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeNUXSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Update Nux Settings',
                'verbose_name_plural': 'Update Nux Settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('IspToolboxAccounts.newuserexperience',),
        ),
    ]
