# Generated by Django 3.1.12 on 2021-07-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0007_changenuxsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserexperience',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
