# Generated by Django 3.1.12 on 2021-07-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0008_newuserexperience_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeNUXSettings',
        ),
    ]
