# Generated by Django 3.1.12 on 2021-07-29 21:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0009_delete_changenuxsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserexperience',
            name='description',
            field=models.CharField(blank=True, help_text='Description of what the nux does', max_length=255),
        ),
        migrations.AlterField(
            model_name='newuserexperience',
            name='name',
            field=models.CharField(help_text='Name of the new user experience - used for template tags. Must be unique', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='newuserexperience',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users that have seen the nux', to=settings.AUTH_USER_MODEL),
        ),
    ]
