# Generated by Django 3.1.12 on 2021-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('IspToolboxAccounts', '0010_auto_20210729_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserexperience',
            name='anonymous_sessions',
            field=models.ManyToManyField(blank=True, help_text='Anonymous Users - cookie based sessions', to='sessions.Session'),
        ),
    ]
