# Generated by Django 3.1.13 on 2021-09-28 23:44
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0011_superuser'),
        ('IspToolboxAccounts', '0011_newuserexperience_anonymous_sessions'),
    ]

    operations = [
    ]
