# Generated by Django 3.1.13 on 2021-10-18 22:20
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0014_auto_20211018_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='business_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('wireless', 'Wireless'), ('coax', 'Coax'), ('fiber', 'Fiber')], max_length=128), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='company_goal',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('start_business', 'Start an ISP Business'), ('customer_acquistion', 'Acquire more customers'), ('expansion', 'Expand service to new areas')], max_length=128), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='individual_role',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bus_fin', 'Business & Finance'), ('tech_install', 'Tech & Installation'), ('mar_sales', 'Marketing & Sales')], max_length=128), default=[], size=None),
            preserve_default=False,
        ),
    ]
