# Generated by Django 3.1.13 on 2021-12-15 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0017_auto_20211215_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagevisit',
            name='ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
