# Generated by Django 3.1.14 on 2022-03-01 22:21
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0019_auto_20220201_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='useragent',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
