# Generated by Django 3.1.14 on 2022-03-28 18:11
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxAccounts', '0020_pagevisit_useragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='isptoolboxusersignupinfo',
            name='contact_me',
            field=models.BooleanField(default=False),
        ),
    ]
