# Generated by Django 3.1.13 on 2021-11-05 21:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_data', '0005_hrslusa15'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrslBra15',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'hrsl_bra_1_5',
                'managed': False,
            },
        ),
    ]
