# Generated by Django 3.1.1 on 2020-10-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overlay', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Overlay',
        ),
    ]
