# Generated by Django 3.1.14 on 2022-04-12 17:13
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0105_delete_pointtopointserviceability'),
        ('api', '0005_pointtopointserviceability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtopointserviceability',
            name='ptp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.pointtopointlink'),
        ),
    ]
