# Generated by Django 3.1.6 on 2021-03-25 17:22
# (c) Meta Platforms, Inc. and affiliates. Copyright

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0002_auto_20210325_0104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MlabUszip1052020',
        ),
        migrations.DeleteModel(
            name='StandardizedMlab',
        ),
        migrations.DeleteModel(
            name='StandardizedPostal',
        ),
    ]
