# Generated by Django 3.0.8 on 2020-09-15 23:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0003_marketevaluatorpipeline_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAccount',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fbid', models.BigIntegerField(editable=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='marketevaluatorpipeline',
            options={'ordering': ('created',)},
        ),
        migrations.CreateModel(
            name='MarketingAudience',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('include_geojson', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('exclude_geojson', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IspToolboxApp.MarketingAccount')),
            ],
        ),
    ]
