# Generated by Django 3.1.12 on 2021-08-04 23:16
# (c) Meta Platforms, Inc. and affiliates. Copyright

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0003_auto_20210325_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlabUszip1052020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_column='State', max_length=5)),
                ('zipcode', models.DecimalField(db_column='Zipcode', decimal_places=65535, max_digits=65535)),
                ('download_mbit_s_field', models.DecimalField(db_column='Download (Mbit/s)', decimal_places=65535, max_digits=65535)),
                ('upload_mbit_s_field', models.DecimalField(db_column='Upload (Mbit/s)', decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'mlab_uszip_10_5_2020',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardizedMlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down', models.DecimalField(blank=True, db_column='down', decimal_places=65535, max_digits=65535, null=True)),
                ('up', models.DecimalField(blank=True, db_column='up', decimal_places=65535, max_digits=65535, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalcode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'standardized_mlab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardizedPostal',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'standardized_postal',
                'managed': False,
            },
        ),
    ]
