# Generated by Django 3.0.8 on 2020-09-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0004_auto_20200916_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkplan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Form477Jun2019',
        ),
        migrations.DeleteModel(
            name='Tl2019BlocksCensus',
        ),
        migrations.DeleteModel(
            name='NetworkPlan',
        ),
    ]
