# Generated by Django 3.1.13 on 2021-11-15 21:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0005_gadm36bra2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedMlabGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('up', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'standardized_mlab_global',
                'managed': False,
            },
        ),
    ]
