# Generated by Django 3.0.8 on 2020-09-28 21:43

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0005_auto_20200917_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingPinConversion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('include', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('exclude', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('num_pins', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)])),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
                ('include_output', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
