# Generated by Django 3.0.8 on 2020-10-05 20:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0006_marketingpinconversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MlabUszip1052020',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_column='State', max_length=5)),
                ('zipcode', models.DecimalField(db_column='Zipcode', decimal_places=65535, max_digits=65535)),
                ('download_mbit_s_field', models.DecimalField(db_column='Download (Mbit/s)', decimal_places=65535, max_digits=65535)),
                ('upload_mbit_s_field', models.DecimalField(db_column='Upload (Mbit/s)', decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'mlab_uszip_10_5_2020',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tl2019UsZcta510',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('zcta5ce10', models.CharField(blank=True, max_length=5, null=True)),
                ('geoid10', models.CharField(blank=True, max_length=5, null=True)),
                ('classfp10', models.CharField(blank=True, max_length=2, null=True)),
                ('mtfcc10', models.CharField(blank=True, max_length=5, null=True)),
                ('funcstat10', models.CharField(blank=True, max_length=1, null=True)),
                ('aland10', models.FloatField(blank=True, null=True)),
                ('awater10', models.FloatField(blank=True, null=True)),
                ('intptlat10', models.CharField(blank=True, max_length=11, null=True)),
                ('intptlon10', models.CharField(blank=True, max_length=12, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'tl_2019_us_zcta510',
                'managed': False,
            },
        ),
    ]
