# Generated by Django 3.1.1 on 2020-10-27 21:22

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0007_mlabuszip1052020_tl2019uszcta510'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardizedMlab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down', models.DecimalField(blank=True, db_column='down', decimal_places=65535, max_digits=65535, null=True)),
                ('up', models.DecimalField(blank=True, db_column='up', decimal_places=65535, max_digits=65535, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalcode', max_length=10, null=True)),
            ],
            options={
                'db_table': 'standardized_mlab',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StandardizedPostal',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('geog', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'standardized_postal',
                'managed': False,
            },
        ),
    ]
