# Generated by Django 3.1.1 on 2020-11-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0009_auto_20201030_0031'),
        ('IspToolboxApp', '0009_tl2019uscounty'),
    ]

    operations = [
    ]
