# Generated by Django 3.1.1 on 2020-11-30 23:26

import IspToolboxApp.Models.MarketEvaluatorModels
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0010_merge_20201105_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsocketToken',
            fields=[
                ('token', models.CharField(default=IspToolboxApp.Models.MarketEvaluatorModels.createTokenDefault, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('expiry', models.DateTimeField(default=IspToolboxApp.Models.MarketEvaluatorModels.createDateExpiryDefault, editable=False)),
            ],
        ),
    ]
