# Generated by Django 3.1.1 on 2021-02-05 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IspToolboxApp', '0011_websockettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvaluatorSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Market Evaluator Summary',
                'verbose_name_plural': 'Market Evaluator Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('IspToolboxApp.marketevaluatorpipeline',),
        ),
    ]
