# Generated by Django 3.0.8 on 2020-07-18 21:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('input_geometryCollection', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('imagesToLoad', models.IntegerField(default=0)),
                ('imagesLoaded', models.IntegerField(default=0)),
                ('inferencesRun', models.IntegerField(default=0)),
                ('inferenceComplete', models.BooleanField(default=False)),
                ('thresholdComplete', models.BooleanField(default=False)),
                ('polygonalizationComplete', models.BooleanField(default=False)),
                ('output_geometryCollection', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
