# Generated by Django 3.0.8 on 2020-07-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingdetection',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
