const SERVICEABLE_BUILDINGS_COLOR = '#34eb46';
const UNSERVICEABLE_BUILDINGS_COLOR = '#ff2f00';
const UNKNOWN_BUILDINGS_COLOR = '#ccc';

export { SERVICEABLE_BUILDINGS_COLOR, UNSERVICEABLE_BUILDINGS_COLOR, UNKNOWN_BUILDINGS_COLOR };
