# Generated by Django 3.1.1 on 2020-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataUpdate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
